Added declarative helmfile
aklivity/zilla pull request #1054
Opened 2024-05-25 22:37 UTC by ttimot24

## Description

A simple declarative way to deploy Zilla to Kubernetes with Helm as described in [Zilla HelmChart docs](https://artifacthub.io/packages/helm/zilla/zilla#configuration).

#### helmfile
https://helmfile.readthedocs.io/

```sh
helmfile apply
```

2024-05-28 13:32 UTC, vordimous commented on cloud/helm-chart/src/main/helm/zilla/helmfile.yaml
> +  version: 0.9.81
I think we will need a way to dynamically set this field right @attilakreiner?

2024-05-29 07:56 UTC, attilakreiner requested changes
Let's change the hardcoded version number to `^0.9.0` please.

2024-05-29 07:56 UTC, attilakreiner commented on cloud/helm-chart/src/main/helm/zilla/helmfile.yaml
> +  version: 0.9.81
My suggestion is that we go with `^0.9.0` so it is consistent with our examples e.g. [setup.sh#L6](https://github.com/aklivity/zilla-examples/blob/fdbcf7c819de9cae3e221219fa70d132a922d343/tcp.echo/setup.sh#L6)

2024-05-30 07:54 UTC, ttimot24 commented
@vordimous @attilakreiner The file is updated with the recommended version range

2024-05-30 07:54 UTC, attilakreiner approved these changes

2024-05-30 14:21 UTC, vordimous approved these changes

2024-05-31 14:32 UTC, jfallows approved these changes

2024-05-31 14:32 UTC, merged