SSE asyncapi server, client
aklivity/zilla pull request #1085
Opened 2024-06-10 10:33 UTC by bmaidics

2024-06-13 09:29 UTC, bmaidics commented
Depends on https://github.com/aklivity/zilla/pull/1092

2024-06-13 17:30 UTC, jfallows requested changes

2024-06-13 17:30 UTC, jfallows commented on runtime/binding-asyncapi/src/main/java/io/aklivity/zilla/runtime/binding/asyncapi/config/AsyncapiParser.java
> +        schemas.put("3.0.2", schema("3.0.2_zilla"));
The version key should also be `3.0.2-zilla` to not conflict with an actual 3.0.2 release of the standard.

2024-06-13 17:30 UTC, jfallows commented on runtime/common/src/main/java/io/aklivity/zilla/runtime/common/feature/FeatureFilter.java
> +    public static final boolean INCUBATOR_ENABLED = incubatorEnabled();
Perhaps we could instead use the `featureEnabled` static method, making it `public`?

2024-06-18 04:35 UTC, jfallows submitted a review, later dismissed

2024-06-18 13:04 UTC, jfallows approved these changes

2024-06-18 13:04 UTC, merged