create `function` support in `risingwave` binding
aklivity/zilla pull request #1248
Opened 2024-09-16 16:23 UTC by ankitk-me

2024-09-16 19:10 UTC, jfallows requested changes

2024-09-16 19:10 UTC, jfallows commented on incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/schema/risingwave.schema.patch.json
> +                                                    ]
This is not needed and should be reverted.

2024-09-16 19:10 UTC, jfallows commented on incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/config/proxy.function.yaml
> +              - "CREATE FUNCTION"
We are not routing `CREATE FUNCTION` to a different `exit`, it is going to the same `exit`, just appending the `UDF` server URL information to it on the way through, right?

2024-09-16 19:10 UTC, jfallows commented on incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/streams/pgsql/create.function/client.rpt
> +      [0x00]
This is the `sql` that is being sent from the client, so wouldn't include the `using LINK http://localhost:8815;` because that's getting injected implicitly by the `risingwave` binding, right?

2024-09-16 19:10 UTC, jfallows commented on incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/streams/pgsql/create.function/server.rpt
> +      "AS series;"
Yes, like this - just need to make sure the pure spec scripts are consistent so the spec ITs can pass.

2024-09-16 19:10 UTC, jfallows commented on incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/config/proxy.function.yaml
> +        url: http://localhost:8815
We can predict that we'll need separate UDF servers for different languages, such as `java` and `python` over time, even though we are starting with `java` first.

Please make sure we design a syntax that can remain backwards compatible and feels natural when adding `python` UDF server later.

```suggestion
    options:
      udf:
        - server: http://localhost:8815
          language: java # default
```

Initially this array can have max length 1 similar to catalogs.

Later, when we add support for `python`, we can host different user-defined functions on different servers as needed.

```suggestion
    options:
      udf:
        - server: http://udf.zillabase.dev:8815
          language: java # default
        - server: http://udf-python.zillabase.dev:8815
          language: python
```

If needed (even later!), we can further enhance this to host different UDFs on different servers, even for the same language, by adding a pattern for matching UDF names on a specific server.  Then the injection of the `USING LINK` value would be dependent on the UDF name and match a bit like routing.

2024-09-16 19:10 UTC, jfallows commented on incubator/binding-risingwave/src/main/java/io/aklivity/zilla/runtime/binding/risingwave/internal/config/RisingwaveOptionsConfigAdapter.java
> +            options.udf(udf.adaptFromJson(object.getJsonObject(UDF_NAME)));
See specification feedback about options syntax.

2024-09-17 13:56 UTC, ankitk-me commented on incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/schema/risingwave.schema.patch.json
> +                                                    ]
done

2024-09-17 13:56 UTC, ankitk-me commented on incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/config/proxy.function.yaml
> +              - "CREATE FUNCTION"
done

2024-09-18 05:13 UTC, jfallows requested changes

2024-09-18 05:13 UTC, jfallows commented on incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/config/proxy.function.yaml
> +              - strategy: topic
Can this be removed now?
(also catalog)

2024-09-18 05:13 UTC, jfallows commented on incubator/binding-risingwave/src/main/java/io/aklivity/zilla/runtime/binding/risingwave/config/RisingwaveUdfConfigBuilder.java
> +        String language = this.language != null ? this.language : "java";
Please hoist this `"java"` string as a constant, such as `LANGUAGE_DEFAULT`.

2024-09-18 05:13 UTC, jfallows commented on incubator/binding-risingwave/src/test/java/io/aklivity/zilla/runtime/binding/risingwave/internal/config/RisingwaveOptionsConfigAdapterTest.java
> +                    ]
Please include `udf` in `shouldWriteOptions` test method implementation as well.

2024-09-18 13:06 UTC, jfallows requested changes

2024-09-18 13:06 UTC, jfallows commented on incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/schema/risingwave.schema.patch.json
> +                                },
The `language` above should be `"const": "java"` too, right?
Since we only support the value "java" if present for now.

2024-09-18 16:16 UTC, jfallows approved these changes

2024-09-18 16:16 UTC, merged