Update schemas to catalog z related queries into a separate schema and make  public schema as default
aklivity/zilla pull request #1329
Opened 2024-11-14 00:28 UTC by akrambek

## Description

Update schemas to catalog z related queries into a separate schema and make  public schema as default

2024-11-14 01:03 UTC, jfallows commented on incubator/binding-pgsql/src/main/antlr4/io/aklivity/zilla/runtime/binding/pgsql/parser/PostgreSqlParser.g4
> +    | ZTABLE
```suggestion
    | ZSTREAM
    | ZTABLE
    | ZVIEW
```
(alphabetical)

2024-11-14 01:03 UTC, jfallows commented on incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/streams/pgsql/create.zstream.with.includes/client.rpt
> +write "CREATE ZSTREAM weather (\n"
Let's call this `commands` instead so it fits better to have reply-to `replies`, and structure the columns accordingly.

2024-11-14 01:03 UTC, jfallows commented on incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/streams/pgsql/create.zstream.with.includes/client.rpt
> +      "    function = compute_status_and_correlation_id,\n"
We need to create these too, so that the example is self-documenting and self-consistent, agree?

Also, after this first pass, we wanted the `function` to become less aware of correlation_id, and handle that implicitly, agreed?

How do we route specific commands to specific functions?
This seems to currently imply every function has its own ZSTREAM and therefore it's own pair of command and reply topics.

2024-11-27 06:51 UTC, jfallows reviewed
How many `root` `pgsql` connections are created to `risingwave` per regular user `pgsql` connection to `zilla`?

2024-11-27 06:51 UTC, jfallows commented on incubator/binding-pgsql/src/test/java/io/aklivity/zilla/runtime/binding/pgsql/parser/PgsqlParserTest.java
> +        String sql = "DROP ZVIEW test_view;";
Should this change be reverted since this is `shouldParseDropView()` and we also have a separate `shouldParseDropZView()` ?

2024-11-27 06:51 UTC, jfallows commented on incubator/binding-risingwave.spec/src/main/scripts/io/aklivity/zilla/specs/binding/risingwave/streams/effective/alter.stream.add.column/server.rpt
> +read zilla:begin.ext ${pgsql:beginEx()
```suggestion
read zilla:begin.ext ${pgsql:matchBeginEx()
```

Same feedback for other scripts, where we are reading the pgsql begin extension.

2024-11-27 06:51 UTC, jfallows commented on incubator/binding-risingwave/src/main/java/io/aklivity/zilla/runtime/binding/risingwave/internal/stream/RisingwaveProxyFactory.java
> +
We should discuss the design problem you are trying to solve with this approach.

2024-11-27 07:37 UTC, akrambek commented on incubator/binding-pgsql/src/test/java/io/aklivity/zilla/runtime/binding/pgsql/parser/PgsqlParserTest.java
> +        String sql = "DROP ZVIEW test_view;";
yep

2024-11-27 07:38 UTC, akrambek commented
One

2024-12-09 15:35 UTC, jfallows requested changes

2024-12-09 15:35 UTC, jfallows commented on incubator/binding-pgsql/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/parser/listener/SqlAlterStreamTopicListener.java
>      private final List<AlterExpression> alterExpressions = new ArrayList<>();
Please move `final` field up with other `final` fields and initialize in constructor as it is not a (pseudo-) constant.

2024-12-09 15:35 UTC, jfallows commented on incubator/binding-pgsql/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/parser/listener/SqlAlterTableTopicListener.java
>      private final List<AlterExpression> alterExpressions = new ArrayList<>();
Same feedback.

2024-12-09 15:35 UTC, jfallows commented on incubator/binding-pgsql/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/parser/listener/SqlCreateStreamListener.java
> +        schema = split.length > 1 ? split[0] : "public";
Please move this default `"public"` to a constant.

2024-12-09 15:35 UTC, jfallows commented on incubator/binding-pgsql/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/parser/listener/SqlCreateTableTopicListener.java
> +        schema = split.length > 1 ? split[0] : "public";
Same feedback.

2024-12-09 15:35 UTC, jfallows commented on incubator/binding-pgsql/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/parser/listener/SqlCreateZviewListener.java
> +        schema = split.length > 1 ? split[0] : "public";
Same feedback.

2024-12-09 15:35 UTC, jfallows commented on incubator/binding-pgsql/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/parser/listener/SqlDropListener.java
> +            String schema = split.length > 1 ? split[0] : "public";
Same feedback.

2024-12-09 15:35 UTC, jfallows commented on incubator/binding-pgsql/src/test/java/io/aklivity/zilla/runtime/binding/pgsql/parser/PgsqlParserTest.java
> +    public void shouldCreateTableParseWithPrimaryKeysSql()
```suggestion
    public void shouldCreateTableWithPrimaryKey()
```
works?

Note: we are in the parser test class, so no need to use parse in the name of any of the test methods, please review all of the test method names.

2024-12-09 15:35 UTC, jfallows commented on incubator/binding-pgsql/src/test/java/io/aklivity/zilla/runtime/binding/pgsql/parser/PgsqlParserTest.java
>      public void shouldHandleEmptyDropStatement()
```suggestion
    public void shouldDropTable()
```

2024-12-09 15:35 UTC, jfallows commented on incubator/binding-risingwave/src/main/java/io/aklivity/zilla/runtime/binding/risingwave/internal/stream/RisingwaveProxyFactory.java
> +
I think we discussed changing this, where `zillabase` is the system user that could potentially be done just once (per core). Let me know if there are any changes you'd like to make to prepare for that and we can file an enhancement to track the optimization for after the feature work is completed.

2024-12-11 18:03 UTC, jfallows requested changes

2024-12-11 18:03 UTC, jfallows commented on incubator/binding-pgsql-kafka/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/kafka/internal/schema/PgsqlKafkaKeyAvroSchemaTemplate.java
> +        CreateTable createTable)
```suggestion
        CreateTable command)
```
Seems more readable, agreed?

Let's update the other `generate` methods too, so it's all consistent.

2024-12-11 18:03 UTC, jfallows commented on incubator/binding-pgsql/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/parser/model/Alter.java
>  public record Alter(
`AlterZView` `AlterZTable` ?

2024-12-11 18:03 UTC, jfallows commented on incubator/binding-pgsql/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/parser/model/CreateStream.java
> +public record CreateStream(
`CreateZStream`?

2024-12-11 18:03 UTC, jfallows commented on incubator/binding-pgsql/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/parser/model/CreateTable.java
> +public record CreateTable(
```
CreateZTable
```
?

2024-12-11 18:45 UTC, akrambek commented on incubator/binding-pgsql/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/parser/model/CreateStream.java
> +public record CreateStream(
it will be in another PR

2024-12-11 18:49 UTC, akrambek commented on incubator/binding-pgsql/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/parser/model/CreateTable.java
> +public record CreateTable(
it is covered in ZTABLE PR

2024-12-11 19:01 UTC, akrambek commented on incubator/binding-pgsql/src/main/java/io/aklivity/zilla/runtime/binding/pgsql/parser/model/Alter.java
>  public record Alter(
we don't support alter zview and ztable is addressed in Ztable PR

2024-12-13 01:01 UTC, jfallows approved these changes

2024-12-13 01:01 UTC, merged