Fix failing test when JVM default locale is not US
aklivity/zilla pull request #1359
Opened 2024-12-24 03:06 UTC by epieffe

## Description
The test [PrometheusMetricsPrinterTest.shouldWorkWithMilliseconds()](https://github.com/aklivity/zilla/blob/b3f686c8d6646a3affeba4c2668da0a7801dd3cd/runtime/exporter-prometheus/src/test/java/io/aklivity/zilla/runtime/exporter/prometheus/internal/printer/PrometheusMetricsPrinterTest.java#L104) fails when the default JVM locale does not use  dot (`.`) as the decimal separator, because floating point numbers are formatted differently and the string comparison does not match.

**Solution**: explicitly set the locale to `Locale.US` when formatting decimal numbers. This makes the test pass regardless of the JVM locale settings and generally ensures more consistent behaviour because the output is independent from the JVM local configuration.

2025-03-13 01:03 UTC, jfallows requested changes

2025-03-13 01:03 UTC, jfallows commented on runtime/exporter-prometheus/src/main/java/io/aklivity/zilla/runtime/exporter/prometheus/internal/printer/PrometheusMetricsPrinter.java
>              "%s{namespace=\"%s\",binding=\"%s\"} %f";
```suggestion
            "%s{namespace=\"%s\",binding=\"%s\"} %s";
```

If we use `%s` formatter specifier instead, then `double` will box to `Double` and call `Double.toString()` which is locale-independent, so no need to specify locale variant of `String.format(...)`, agree?

2025-03-15 01:01 UTC, epieffe commented on runtime/exporter-prometheus/src/main/java/io/aklivity/zilla/runtime/exporter/prometheus/internal/printer/PrometheusMetricsPrinter.java
>              "%s{namespace=\"%s\",binding=\"%s\"} %f";
Yes, agreed! Thanks!

2025-03-17 19:04 UTC, jfallows approved these changes

2025-03-17 20:18 UTC, merged