Flyweight wrapping error race condition fix
aklivity/zilla pull request #161
Opened 2023-02-05 15:11 UTC by aDaemonThread

fix #146

2023-02-05 15:14 UTC, aDaemonThread commented on runtime/binding-http/src/main/java/io/aklivity/zilla/runtime/binding/http/internal/stream/HttpServerFactory.java
> +        }
@jfallows Do you think we need to update `HEADER_SERVER` as well? In the earlier static declaration we don't have this attribute?

2023-02-05 17:54 UTC, aDaemonThread commented on runtime/binding-http/src/main/java/io/aklivity/zilla/runtime/binding/http/internal/stream/HttpServerFactory.java
> +        }
Update: Removed `HEADER_SERVER` attribute from newly added method `initHeadersEmpty` as it was causing the related ITs to fail.

2023-02-06 21:14 UTC, jfallows approved these changes

2023-02-06 21:17 UTC, jfallows requested changes

2023-02-06 21:17 UTC, jfallows commented on runtime/binding-http/src/main/java/io/aklivity/zilla/runtime/binding/http/internal/stream/HttpServerFactory.java
> +
Let's include the `server` header when explicitly specified, same as `initHeaders`.

2023-02-10 20:23 UTC, jfallows approved these changes

2023-02-10 20:27 UTC, merged