Engine support to exporters
aklivity/zilla pull request #202
Opened 2023-04-14 07:23 UTC by attilakreiner

2023-04-14 21:00 UTC, jfallows requested changes
I noticed that some of the new files in `runtime/engine` are missing the license header, which should have been caught by our build.

Turns out we are not checking in `runtime/engine`, just everywhere else. 🙂 

I've create a PR to fix this on `develop` and will merge it soon, plus catch up to `feature/telemetry-metrics` too.

In the meantime, please run the following command to fix up the license headers in each source file.

```
./mvnw license:format
```

2023-04-14 21:00 UTC, jfallows commented on runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/exporter/Exporter.java
> +    }
I think we can remove this method as we're not calling it anywhere, right?

2023-04-14 21:00 UTC, jfallows commented on runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/exporter/TestExporterContext.java
> +public class TestExporterContext implements ExporterContext
Please add a blank line between imports and class definition.

2023-04-17 07:37 UTC, attilakreiner commented on runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/exporter/Exporter.java
> +    }
done

2023-04-17 07:37 UTC, attilakreiner commented on runtime/engine/src/test/java/io/aklivity/zilla/runtime/engine/test/internal/exporter/TestExporterContext.java
> +public class TestExporterContext implements ExporterContext
done

2023-04-17 19:33 UTC, jfallows approved these changes

2023-04-17 19:33 UTC, merged