Implement counter value reader in EngineExtContext
aklivity/zilla pull request #252
Opened 2023-05-24 15:25 UTC by attilakreiner

## Description
Implement counter value reader in EngineExtContext

2023-05-24 17:29 UTC, jfallows requested changes

2023-05-24 17:29 UTC, jfallows commented on runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/metrics/LayoutManager.java
> +public class LayoutManager
Suggest we rename this to MetricsLayoutManager and move to `layouts` package.

2023-05-24 17:29 UTC, jfallows commented on runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/metrics/MetricsProcessor.java
Suggest we keep the API limited to accessing specific (namespaced) binding metric, and leave all the decisions about how to output at the calling side, as this will different significantly for `zilla metrics`, various `exporters`, etc.

There is also a question of discovery, that we can add here as well, to find the list of all metrics recorded for each binding.

Then callers such as `zillla metrics`, `exporters`, etc can discover the full list of recorded metrics, request the accessors for each metric once, and implement their own logic for collecting and exporting the current metric values in the appropriate format.

2023-05-24 18:20 UTC, attilakreiner commented on runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/metrics/LayoutManager.java
> +public class LayoutManager
We have a `layout.metrics` package, I moved it there and kept the name. How about it?

2023-05-24 18:25 UTC, attilakreiner commented on runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/metrics/MetricsProcessor.java
For now, I removed the `print` method, so the only public method is `findRecord` that was just added now. This resulted in some cleanup. This is not the final version, as you pointed out this class will definitely need some more changes when we reconcile all the use cases. However, I think it's good enough for now to get you unblocked. The next iteration where all the use cases (engine, command, exporter) will be using the same class should come in a next PR.

2023-05-25 11:04 UTC, attilakreiner commented on runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/internal/metrics/MetricsProcessor.java
I added the `getRecords` method to get the list of all metric records. I also made the string formatter functions injected in the constructor. This is a necessary step to generalize the `MetricsProcessor` so it can eventually be used by the command & exporter. This way I was able to add back all the unit tests I temporarily removed in a slightly modified form (the tests are checking the metric record values directly instead of the printed output).

2023-05-25 18:43 UTC, jfallows requested changes

2023-05-25 18:43 UTC, jfallows commented on runtime/engine/src/main/java/io/aklivity/zilla/runtime/engine/Engine.java
> +        }
We need to do more of a review on `MetricRecord` etc before we consider pulling it up into `engine`. Please move it back into `command-metrics` for now.

In the meantime, let's simplify.
 - lookup `bindingId` and `metricId` based on provided `namespace`, `binding` and `metric` names from label manager
 - keep the dispatchers parameter to the constructor and retain in a field
 - walk the dispatchers to find a `LongSupplier` for each `counter`
 - in DispatcherAgent.supplyCounter(bindingId, metricId), return countersLayout.suppyReader(bindingId, metricId)
 - return an aggregating `LongSupplier` lambda that sums all the `LongSupplier`s to get the total counter value

2023-07-07 08:07 UTC, closed without merging