Validator WIP
aklivity/zilla pull request #412
Opened 2023-09-14 08:18 UTC by attilakreiner

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

2023-09-15 04:45 UTC, jfallows requested changes

2023-09-15 04:45 UTC, jfallows commented on runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/validator/config/SchemaConfig.java
> +    public int id;
Please make these fields `final`.

2023-09-15 07:29 UTC, attilakreiner commented on runtime/binding-kafka/src/main/java/io/aklivity/zilla/runtime/binding/kafka/internal/validator/config/SchemaConfig.java
> +    public int id;
done

2023-09-19 00:00 UTC, jfallows approved these changes

2023-09-19 00:03 UTC, merged