Fix: Added Contribution Section to Readme
aklivity/zilla pull request #550
Opened 2023-10-31 03:21 UTC by Kalyanimhala

Fixes #545
Successfully added Contributions section to the Readme.md.
@jfallows review it and merged the PR. Thank You!

2023-10-31 15:43 UTC, Kalyanimhala commented
@jfallows Please review my PR!

2023-10-31 17:04 UTC, jfallows requested changes

2023-10-31 17:04 UTC, jfallows commented on CODE_OF_CONDUCT.md
> +# Contributor Covenant Code of Conduct
We already have a CODE_OF_CONDUCT.md at the standard location.
Please see https://github.com/aklivity/zilla/blob/develop/.github/CODE_OF_CONDUCT.md.

2023-10-31 17:04 UTC, jfallows commented on README.md
> +</a>
The repository should be `aklivity/zilla` instead of `jfallows/zilla`.

2023-10-31 17:06 UTC, jfallows requested changes

2023-10-31 17:06 UTC, jfallows commented on README.md
> +### All Thanks To Our Contributors:
```suggestion
### Many thanks to our contributors!
```

2023-11-02 00:47 UTC, jfallows approved these changes

2023-11-02 00:48 UTC, jfallows approved these changes

2023-11-02 00:49 UTC, merged