Use env var to add incubator java option
aklivity/zilla pull request #811
Opened 2024-02-25 14:20 UTC by vordimous

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #800

2024-02-26 18:57 UTC, jfallows requested changes

2024-02-26 18:57 UTC, jfallows commented on manager/src/main/java/io/aklivity/zilla/manager/internal/commands/install/ZpmInstall.java
> +                "[ \"$ZILLA_INCUBATOR_ENABLED\" = \"true\" ] && JAVA_OPTIONS=\"$JAVA_OPTIONS -Dzilla.incubator.enabled=true\"",
```suggestion
                "[ \"$ZILLA_INCUBATOR_ENABLED\" != \"\" ] && JAVA_OPTIONS=\"$JAVA_OPTIONS -Dzilla.incubator.enabled=$ZILLA_INCUBATOR_ENABLED\"",
```

Note: we need this to work for both explicit `true` and explicit `false` scenarios.
```
ZILLA_INCUBATOR_ENABLED=true ./zilla
```
for releases where incubator is disabled by default, and
```
ZILLA_INCUBATOR_ENABLED=false ./zilla
```
for local `develop-SNAPSHOT` builds, where incubator is enabled by default.

2024-02-26 21:12 UTC, vordimous commented
@jfallows changes committed and modified to use `-z` to check if the env var is set.

2024-02-26 23:11 UTC, jfallows submitted a review, later dismissed

2024-02-27 01:22 UTC, jfallows approved these changes

2024-02-27 05:51 UTC, merged