Implement filesystem catalog
aklivity/zilla pull request #962
Opened 2024-04-17 08:55 UTC by bmaidics

2024-04-17 09:12 UTC, bmaidics commented
@jfallows , please check the last commit: https://github.com/aklivity/zilla/pull/962/commits/28696c7f31fb4bc66ac033b4b9e0da263fb09fbc
First I took another approach to get reference for the readURL in the namespace config and I can't decide for sure which one is better. Get it from the adaptContext, or directly set it for every catalog? I have a feeling adaptContext will be the winner though.

2024-04-19 02:08 UTC, jfallows requested changes

2024-04-19 02:08 UTC, jfallows commented on incubator/catalog-filesystem.spec/src/main/scripts/io/aklivity/zilla/specs/catalog/filesystem/config/asyncapi/mqtt.yaml
> +defaultContentType: application/json
Missing newline at EOF

2024-04-19 02:08 UTC, jfallows commented on incubator/catalog-filesystem.spec/src/main/scripts/io/aklivity/zilla/specs/catalog/filesystem/schema/filesystem.schema.patch.json
> +                                            "url":
`path`

2024-04-19 02:08 UTC, jfallows commented on incubator/catalog-filesystem/src/main/java/io/aklivity/zilla/runtime/catalog/filesystem/internal/FilesystemCatalogHandler.java
> +
Remove extra blank lines.

2024-04-19 02:08 UTC, jfallows commented on incubator/catalog-filesystem/src/main/java/io/aklivity/zilla/runtime/catalog/filesystem/internal/FilesystemCatalogHandler.java
> +    {
Method formatting

2024-04-19 02:08 UTC, jfallows commented on incubator/catalog-filesystem/src/main/java/io/aklivity/zilla/runtime/catalog/filesystem/internal/FilesystemCatalogHandler.java
> +            String schema = readURL.apply(config.url);
Use `EngineContext.resolvePath` like `FileSystemVault` instead of `readURL`.

2024-04-19 02:08 UTC, jfallows commented on incubator/catalog-filesystem/src/main/java/io/aklivity/zilla/runtime/catalog/filesystem/internal/config/FilesystemSchemaConfigBuilder.java
> +    public FilesystemSchemaConfigBuilder<T> url(
`path`

2024-04-19 02:09 UTC, jfallows requested changes

2024-04-19 02:09 UTC, jfallows commented on incubator/catalog-filesystem/src/main/java/io/aklivity/zilla/runtime/catalog/filesystem/internal/FilesystemCatalogFactorySpi.java
> +public class FilesystemCatalogFactorySpi implements CatalogFactorySpi
Needs `@Incubating`.

2024-04-19 22:57 UTC, jfallows approved these changes

2024-04-19 22:57 UTC, merged