Support asyncapi mqtt streetlights mapping to kafka streetlights
aklivity/zilla pull request #997
Opened 2024-05-03 11:03 UTC by bmaidics

2024-05-08 03:04 UTC, jfallows requested changes

2024-05-08 03:04 UTC, jfallows commented on runtime/binding-mqtt-kafka/src/main/java/io/aklivity/zilla/runtime/binding/mqtt/kafka/internal/stream/MqttKafkaSessionFactory.java
> +                binding.id, sessionTopic, binding.qos2Supported());
I think this would be better changes to return `publishQosMax` from `binding` and pass that to `MqttSessionProxy` instead of propagating the boolean logic too far.

Also, probably would be better to use the enum instead of an integer to pass into the constructor.

2024-05-08 03:04 UTC, jfallows commented on runtime/binding-mqtt-kafka/src/test/java/io/aklivity/zilla/runtime/binding/mqtt/kafka/internal/stream/MqttKafkaPublishProxyIT.java
> +    @Ignore
Ignore?

2024-05-08 03:04 UTC, jfallows commented on runtime/binding-mqtt-kafka/src/test/java/io/aklivity/zilla/runtime/binding/mqtt/kafka/internal/stream/MqttKafkaPublishProxyIT.java
We need a negative test to reject attempt to publish at `qos2` after establishing maximum qos less than 2.

2024-05-08 08:27 UTC, bmaidics commented on runtime/binding-mqtt-kafka/src/test/java/io/aklivity/zilla/runtime/binding/mqtt/kafka/internal/stream/MqttKafkaPublishProxyIT.java
We have a test in the mqtt binding called: shouldRejectPublishQos2NotSupported
mqtt-kafka binding just communicates in the session reply begin what it supports, it won't reject. mqtt binding will do the reject.

2024-05-08 20:33 UTC, jfallows requested changes

2024-05-08 20:33 UTC, jfallows commented on runtime/binding-mqtt-kafka/src/test/java/io/aklivity/zilla/runtime/binding/mqtt/kafka/internal/stream/MqttKafkaPublishProxyIT.java
Yes, that was already understood when the negative test IT for mqtt-kafka was requested above.

As a general rule, don't overly rely on other bindings to protect a binding from malformed input. That is akin to relying on end-to-end testing instead of having IT coverage for the binding.

Please add a negative test that ensures `qos2` `publish` is rejected at `mqtt-kafka` binding if `mqtt-kafka` binding responds to `mqtt` `session` stream indicating a maximum of `qos1` for `publish`.

2024-05-08 20:33 UTC, jfallows commented on runtime/binding-mqtt-kafka/src/main/java/io/aklivity/zilla/runtime/binding/mqtt/kafka/internal/config/MqttKafkaBindingConfig.java
> +    public MqttQoS publishMaxQos()
Naming consistency.

```suggestion
    public MqttQoS publishQosMax()
```

2024-05-08 20:33 UTC, jfallows commented on runtime/binding-mqtt-kafka/src/main/java/io/aklivity/zilla/runtime/binding/mqtt/kafka/internal/stream/MqttKafkaSessionFactory.java
>              }
??
This should be `this.publishQosMax = publishQosMax.value();`, right?

2024-05-08 20:33 UTC, jfallows commented on specs/binding-mqtt-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/mqtt/kafka/streams/kafka/publish.topic.space.with.params/client.rpt
> +write notify PRODUCE_CONNECTED
Is this `PRODUCE_CONNECTED` barrier needed?
It doesn't seem to be referenced in the ITs.
Let's remove it if possible.

2024-05-08 20:33 UTC, jfallows commented on specs/binding-mqtt-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/mqtt/kafka/streams/mqtt/publish.topic.space.with.params/client.rpt
> +write notify PUBLISH_CONNECTED
Is this `PUBLISH_CONNECTED` barrier needed?
It doesn't seem to be referenced in the ITs.
Let's remove it if possible.

2024-05-09 15:42 UTC, jfallows requested changes

2024-05-09 15:42 UTC, jfallows commented on runtime/binding-mqtt-kafka/src/main/java/io/aklivity/zilla/runtime/binding/mqtt/kafka/internal/stream/MqttKafkaSessionFactory.java
> +                binding.publishQosMax() : this.publishQosMax;
Please add a `MqttQos.min(MqttQos that)` method that returns the `MqttQos` with minimum `.value()`, either `this` or `that`.

```suggestion
            final MqttQoS publishQosMax = this.publishQosMax.min(binding.publishQosMax());
```

2024-05-09 15:42 UTC, jfallows commented on runtime/binding-mqtt-kafka/src/main/java/io/aklivity/zilla/runtime/binding/mqtt/kafka/internal/MqttKafkaConfiguration.java
> +        return MqttQoS.valueOf(PUBLISH_MAX_QOS.getAsInt(this));
Naming consistency.

```suggestion
        return MqttQoS.valueOf(PUBLISH_QOS_MAX.getAsInt(this));
```

2024-05-09 15:42 UTC, jfallows commented on runtime/binding-mqtt-kafka/src/test/java/io/aklivity/zilla/runtime/binding/mqtt/kafka/internal/MqttKafkaConfigurationTest.java
> +        assertEquals(PUBLISH_MAX_QOS.name(), PUBLISH_MAX_QOS_NAME);
Naming consistency.

```suggestion
        assertEquals(PUBLISH_QOS_MAX.name(), PUBLISH_QOS_MAX_NAME);
```

2024-05-09 15:42 UTC, jfallows commented on specs/binding-mqtt-kafka.spec/src/main/scripts/io/aklivity/zilla/specs/binding/mqtt/kafka/streams/kafka/publish.reject.qos2/client.rpt
> +
Remove blank line.

2024-05-09 15:42 UTC, jfallows commented on runtime/binding-mqtt-kafka/src/main/java/io/aklivity/zilla/runtime/binding/mqtt/kafka/internal/MqttKafkaConfiguration.java
> +        PUBLISH_MAX_QOS = config.property("publish.max.qos", 2);
Naming consistency.

```suggestion
        PUBLISH_QOS_MAX = config.property("publish.qos.max", 2);
```

2024-05-09 19:15 UTC, jfallows approved these changes

2024-05-09 19:15 UTC, merged